# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service 
spec: 
  selector: 
    app: angularapphelloworld 
  ports: 
  - protocol: TCP 
    port: 4200 
    targetPort: 4200 
    nodePort: 31000 
  type: NodePort   