apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-deployment 
spec: 
  selector: 
    matchLabels: 
      app: angularapphelloworld 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: angularapphelloworld 
    spec: 
      containers: 
      - name: angularapphelloworld 
        image: iamdarshanshah/sample-angular-app
        ports: 
        - containerPort: 4200
